### ISSUE TITLE
Test DNSRecordGetter with mock DNS

### ISSUE THREAD

**Issue by AlexCarmel** [Mika56/PHP-SPF-Check#12]
Currently we don't have any tests to test `DNSRecordGetter`.  We can use PHPUnit Bridge from symphony framework to mock DNS records. To test ` dns_get_record` we can use:
```
DnsMock::withMockedHosts(array(
    'example.com' => array(
        array(
            'type' => 'A',
            'ip' => '1.2.3.4',
        )
    ),
));
```

**Comment by Mika56** [comment]
I didn't know about this mock, I was looking at starting a Docker container with some DNS server, but this looks way easier :D
Might take a look before the end of the week
