### ISSUE TITLE
Error on Http-foundation with composer

### ISSUE THREAD

**Issue by arnovdlaan** [Mika56/PHP-SPF-Check#14]
When i try to install through composer i get the following error:

`Using version ^1.0 for mika56/spfcheck
./composer.json has been updated
Loading composer repositories with package information                            Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mika56/spfcheck ^1.0 -> satisfiable by mika56/spfcheck[1.0.0].
    - Conclusion: remove symfony/http-foundation v3.1.8
    - Conclusion: don't install symfony/http-foundation v3.1.8
    - mika56/spfcheck 1.0.0 requires symfony/http-foundation 2.8.* -> satisfiable by symfony/http-foundation[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/http-foundation[v2.8.13, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.14, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.15, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.0, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.1, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.10, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.11, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.12, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.2, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.3, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.4, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.5, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.6, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.7, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.8, v3.1.8].
    - Can only install one of: symfony/http-foundation[v2.8.9, v3.1.8].
    - Installation request for symfony/http-foundation (locked at v3.1.8) -> satisfiable by symfony/http-foundation[v3.1.8].
`

I guess its looking for an older version of http-foundation, maybe the requirements can be updated / changed for  this?

**Comment by Mika56** [comment]
You seem to be using Symfony 3.x, while this library depends on the 2.8 version.
I'll try to update this today, I'm only using one class from symfony/http-foundation, so version 3 should work well.

**Comment by arnovdlaan** [comment]
Thanks for the quick reply! 'll wait for the update then.

**Comment by Mika56** [comment]
Can you try now? I've updated to v1.0.1, which should allow symfony/http-foundation:3.*

**Comment by arnovdlaan** [comment]
Yes all is working as it should now, thanks again for the quick reply (and fix)!
