### ISSUE TITLE
check failed

### ISSUE THREAD

**Issue by Pascal76** [Mika56/PHP-SPF-Check#17]
Hi Mika

can you check that please ?

 - bookatable.bounce.ed10.net                         / 96.47.31.237              : FAIL
 - bookatable.bounce.ed10.net                         / 96.47.31.238              : FAIL

Pascal

**Comment by Mika56** [comment]
Hi,

Seems to be working for me:
```
Checking IP 96.47.31.237 with domain bookatable.bounce.ed10.net:
string(1) "+"
```

Any chance you recently updated your SPF records or are having DNS problems?

**Comment by Pascal76** [comment]
<?php

require 'spf/vendor/autoload.php';
use Mika56\SPFCheck\SPFCheck;
use Mika56\SPFCheck\DNSRecordGetter;

///////////////////////////////////////////////////////////////////////////////////////

  $checker = new SPFCheck(new DNSRecordGetter());
  $result = $checker->isIPAllowed('96.47.31.237', 'bookatable.bounce.ed10.net');
  print var_dump($result);

?>

dig +short TXT bookatable.bounce.ed10.net   
"v=spf1 a:bookatable.outbound.ed10.com -all"

dig +short A bookatable.outbound.ed10.com
96.47.31.238
96.47.31.237

**Comment by Pascal76** [comment]
hello
can you reproduce ?

**Comment by Mika56** [comment]
Hi,

Sorry, I'm not able to reproduce:

```
➜  spfcheck git:(master) ✗ php test.php
Checking IP 96.47.31.237 with domain bookatable.bounce.ed10.net:
/var/www/spfcheck/test.php:15:
string(1) "+"
➜  spfcheck git:(master) ✗ dig +short bookatable.bounce.ed10.net TXT
"v=spf1 a:bookatable.outbound.ed10.com -all"
➜  spfcheck git:(master) ✗ dig +short bookatable.outbound.ed10.com A
96.47.31.238
96.47.31.237
```

Are you sure you're running the latest stable version? Only possibility I see here is that you're running an older version that's returning wrong results.

**Comment by Pascal76** [comment]
I did a composer update (I did not do before)
and it works
:)

**Comment by Pascal76** [comment]
Hello again 

`<?php
use Mika56\SPFCheck\SPFCheck;
use Mika56\SPFCheck\DNSRecordGetter;

require('vendor/autoload.php');

$checker = new SPFCheck(new DNSRecordGetter()); // Uses php's dns_get_record method for lookup.
var_dump($checker->isIPAllowed('172.82.227.233', 'm1.email.samsung.com'));
?>`

=> string(2) "PE"

dig +short TXT m1.email.samsung.com |grep spf 
"v=spf1 redirect=__spf.campaign.adobe.com"

There is a problem for this domain begining with 2 "_" with php < 7

`                            if (version_compare(PHP_VERSION, '7', '>=')) {
                                if (!filter_var($domain, FILTER_VALIDATE_DOMAIN)) {
                                    return false;
                                }
                            } else {
                                /** @link http://stackoverflow.com/a/4694816/2898156 */
                                if (!(preg_match('/^([_a-z\d](-*[a-z\d])*)(\.([a-z\d](-*[a-z\d])*))*$/i', $domain) 
                                    && preg_match('/^.{1,253}$/', $domain)
                                    && preg_match('/^[^\.]{1,63}(\.[^\.]{1,63})*$/', $domain))
                                ) {
                                    return false;
                                }
                            }`

**Comment by Mika56** [comment]
Please create a new issue for new bugs.
I've created one for you: #24
