### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Pascal76** [Mika56/PHP-SPF-Check#18]
This time I have a problem with my php 5.6.30
I tested on 5.4.16 and it is ok.

```
<?php

require 'lib/vendor/autoload.php';
use Mika56\SPFCheck\SPFCheck;
use Mika56\SPFCheck\DNSRecordGetter;

///////////////////////////////////////////////////////////////////////////////////////

  $checker = new SPFCheck(new DNSRecordGetter());
  $result = $checker->isIPAllowed('83.206.186.9', 'etam.biz');
  print var_dump($result);

?>
```

[24-Mar-2017 17:47:03 Europe/Paris] PHP Warning:  dns_get_record(): A temporary server error occurred. in /apache_sites/jbm/lib/vendor/mika56/spfcheck/src/DNSRecordGetter.php on line 45
[24-Mar-2017 17:47:03 Europe/Paris] PHP Fatal error:  Uncaught exception 'Mika56\SPFCheck\Exception\DNSLookupException' in /apache_sites/jbm/lib/vendor/mika56/spfcheck/src/DNSRecordGetter.php:47
Stack trace:
#0 /apache_sites/jbm/lib/vendor/mika56/spfcheck/src/SPFCheck.php(252): Mika56\SPFCheck\DNSRecordGetter->resolveA('cme.rc.etam.com')
#1 /apache_sites/jbm/lib/vendor/mika56/spfcheck/src/SPFCheck.php(123): Mika56\SPFCheck\SPFCheck->ipMatchesPart('83.206.186.9', 'mx', 'etam.biz')
#2 /apache_sites/jbm/lib/vendor/mika56/spfcheck/src/SPFCheck.php(87): Mika56\SPFCheck\SPFCheck->doCheck('83.206.186.9', 'etam.biz')
#3 /apache_sites/jbm/lib/vendor/mika56/spfcheck/src/SPFCheck.php(67): Mika56\SPFCheck\SPFCheck->doIsIPAllowed('83.206.186.9', 'etam.biz', true)
#4 /apache_sites/jbm/titi.php(10): Mika56\SPFCheck\SPFCheck->isIPAllowed('83.206.186.9', 'etam.biz')
#5 {main}
  thrown in /apache_sites/jbm/lib/vendor/mika56/spfcheck/src/DNSRecordGetter.php on line 47

**Comment by Mika56** [comment]
Hi Pascal,

The "A temporary server error occurred" is always a DNS related problem.
Either your server was not able to to communicate with some remote DNS server, or the server sent an invalid response.

This seems to have been a temporary problem, as it seems to be working now:
```
➜  spfcheck git:(master) ✗ php test.php
Checking IP 83.206.186.9 with domain etam.biz:
/var/www/spfcheck/test.php:15:
string(1) "+"
```

If you want to handle this kind of errors, you can catch the `Mika56\SPFCheck\Exception\DNSLookupException` exception.

**Comment by Pascal76** [comment]
Hello

I just tested with an other resolv.conf and it works.
So it crashes when I use pdns recursor on my main server.
The other one also use pdns recursor and it does not crash … I will try to investigate deeper.


Pascal


De : Mikael Peigney [mailto:notifications@github.com]
Envoyé : dimanche 26 mars 2017 20:53
À : Mika56/PHP-SPF-Check <PHP-SPF-Check@noreply.github.com>
Cc : Pascal HOARAU <pascal@halogen-consulting.com>; Author <author@noreply.github.com>
Objet : Re: [Mika56/PHP-SPF-Check] PHP Fatal error (#18)


Hi Pascal,

The "A temporary server error occurred" is always a DNS related problem.
Either your server was not able to to communicate with some remote DNS server, or the server sent an invalid response.

This seems to have been a temporary problem, as it seems to be working now:

➜  spfcheck git:(master) ✗ php test.php

Checking IP 83.206.186.9 with domain etam.biz:

/var/www/spfcheck/test.php:15:

string(1) "+"

If you want to handle this kind of errors, you can catch the Mika56\SPFCheck\Exception\DNSLookupException exception.

**Comment by Mika56** [comment]
Hi,
I'm closing this as it has not been updated for months. Feel free to reopen if needed.
