### ISSUE TITLE
Limit recursion

### ISSUE THREAD

**Issue by nrafal** [Mika56/PHP-SPF-Check#3]
Hi!

We had encountered problem with wrong SPF - one of our clients made spf like this:

domain.com TXT "spf=v1 include:domain.com ~all"

Of course it caused endless recursion. Due to this bug/feature https://bugs.php.net/bug.php?id=43187 it's imossible to catch this outside library, so it needs some tweaking in library itself.

**Comment by Mika56** [comment]
Hi,

Indeed, this would cause an infinite recursion.
I don't have any time right now to fix this, but I should be able to work on a fix this weekend ;)

**Comment by Mika56** [comment]
This was fixed in #4
