### ISSUE TITLE
Dependency: symfony/phpunit-bridge

### ISSUE THREAD

**Issue by repat** [Mika56/PHP-SPF-Check#37]
Please allow `symfony/phpunit-bridge` ^5.0, thanks! :)

**Comment by Mika56** [comment]
Hi repat,
I've added symfony/phpunit-bridge 5.* as an allowed dependency.
You can now install version 1.1.5, enjoy!

**Comment by repat** [comment]
Ah, sorry, actually, the problem was also `symfony/http-foundation: 2.8.* || ^3.0 || ^4.0` since the new Laravel has all the `^5.0` symfony components

**Comment by Mika56** [comment]
What about version 1.1.6 ? :)

**Comment by repat** [comment]
That did the trick, thanks for the fast help :)
