### ISSUE TITLE
Spf showing ending

### ISSUE THREAD

**Issue by rccess** [Mika56/PHP-SPF-Check#48]
SPF Generated from code and updated in domain DNS. but showing pending in application (response return-pending) after propagation, and when i am trying to send email  SPF getting passed, can you please help me fix this pending to verified issue

https://prnt.sc/dLHm6T9KhXjF 

https://prnt.sc/X-BByHsafYLy--

**Comment by Mika56** [comment]
This repository is about a library for checking SPF records. If you need help sending emails using your domain name, please contact your web host for their assistance.

**Comment by rccess** [comment]
i am using your repo in my application, but it is return results pending after propagation !

Can you pleas help me on that ?

Thanks
